---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  labels:
    app: c64afbea-74df-11ee-87d2-d707d149d5d0
  name: sb-11-prometheus
  namespace: monitoring
spec:
  serviceName: sb-11-prometheus-daemon
  replicas: 1
  selector:
    matchLabels:
      app: c64afbea-74df-11ee-87d2-d707d149d5d0
  template:
    metadata:
      labels:
        app: c64afbea-74df-11ee-87d2-d707d149d5d0
    spec:
      nodeSelector:
        node-type: worker
      restartPolicy: Always
      containers:

      # ----------------------------------------------------
      - name: prometheus
        image: reg.docker.askug.net:5000/prometheus-sb-11:0.0.5
        args: [
          "--config.file=/etc/prometheus/prometheus.yml",
          "--storage.tsdb.path=/var/lib/prometheus/",
          "--web.console.templates=/etc/prometheus/consoles",
          "--web.console.libraries=/etc/prometheus/console_libraries",
          "--web.external-url=https://prometheus.askug.net",
          "--web.enable-lifecycle"
        ]

        livenessProbe:
          httpGet:
            path: /-/healthy
            port: 9090
          initialDelaySeconds: 5
          periodSeconds: 5

        readinessProbe:
          httpGet:
            path: /-/ready
            port: 9090
          initialDelaySeconds: 3
          periodSeconds: 3

        volumeMounts:
        - mountPath: "/etc/prometheus/prometheus.yml"
          name: monitoring-data-config
          subPath: "prometheus.yml"
          readOnly: true
        - mountPath: "/etc/prometheus/email_rules.yml"
          name: monitoring-data-config
          subPath: "email_rules.yml"
          readOnly: true
        - mountPath: "/etc/prometheus/telegram_rules.yml"
          name: monitoring-data-config
          subPath: "telegram_rules.yml"
          readOnly: true
        - mountPath: "/var/lib/prometheus"
          name: monitoring-data-volume
          subPath: "caches/prometheus"
        - mountPath: "/etc/prometheus/restapi.token"
          name: monitoring-data-config
          subPath: "restapi.token"
          readOnly: true

        ports:
        - containerPort: 9090
          name: tcp9090

        env:
        - name: PROMETHEUS_VERSION
          value: 2.47.0

        resources:
          limits:
            memory: 4Gi
            cpu: "4"
          requests:
            memory: 2Gi
            cpu: "2"

      volumes:
      - name: monitoring-data-secrets
        secret:
          secretName: sb-11-monitoring-secrets
      - name: monitoring-data-config
        configMap:
          name: sb-11-monitoring-config
      - name: monitoring-data-volume
        persistentVolumeClaim:
          claimName: sb-11-monitoring-data

...


---
apiVersion: v1
kind: Service
metadata:
  name: sb-11-monitoring-prometheus-service
  namespace: monitoring
spec:
  selector:
    app: c64afbea-74df-11ee-87d2-d707d149d5d0
  type: ClusterIP
  ports:
    - protocol: TCP
      name: "http-9090"
      port: 9090
      targetPort: 9090

...
