---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: 249dc5be-74e1-11ee-9d65-a310b85ea436
  name: sb-11-alertmanager
  namespace: monitoring
spec:
  replicas: 1
  selector:
    matchLabels:
      app: 249dc5be-74e1-11ee-9d65-a310b85ea436
  template:
    metadata:
      labels:
        app: 249dc5be-74e1-11ee-9d65-a310b85ea436
    spec:
      nodeSelector:
        node-type: worker
      restartPolicy: Always
      containers:

      # ----------------------------------------------------
      - name: alertmanager
        image: reg.docker.askug.net:5000/alertmanager-sb-11:0.0.5
        args: [
          "--web.external-url=https://alertmanager.askug.net",
          "--config.file=/etc/alertmanager/alertmanager.yml"
        ]

        livenessProbe:
          httpGet:
            path: /-/healthy
            port: 9093
          initialDelaySeconds: 5
          periodSeconds: 5

        readinessProbe:
          httpGet:
            path: /-/ready
            port: 9093
          initialDelaySeconds: 3
          periodSeconds: 3

        volumeMounts:
          - mountPath: "/etc/alertmanager/alertmanager.yml"
            name: monitoring-data-config
            subPath: "alertmanager.yml"
            readOnly: true
          - mountPath: "/etc/alertmanager/telegram.token"
            name: monitoring-data-secrets
            subPath: "telegram.token"
            readOnly: true
          - mountPath: "/etc/alertmanager/email.password"
            name: monitoring-data-secrets
            subPath: "email.password"
            readOnly: true

        ports:
        - containerPort: 9093
          name: tcp9093

        env:
        - name: ALERTMANAGER_VERSION
          value: 0.26.0

        resources:
          limits:
            memory: 256Mi
            cpu: 500m
          requests:
            memory: 128Mi
            cpu: 250m

      volumes:
      - name: monitoring-data-secrets
        secret:
          secretName: sb-11-monitoring-secrets
      - name: monitoring-data-config
        configMap:
          name: sb-11-monitoring-config

...


---
apiVersion: v1
kind: Service
metadata:
  name: sb-11-monitoring-alertmanager-service
  namespace: monitoring
spec:
  selector:
    app: 249dc5be-74e1-11ee-9d65-a310b85ea436
  type: ClusterIP
  ports:
    - protocol: TCP
      name: "http-9093"
      port: 9093
      targetPort: 9093

...
