---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: m8-local-storage-monitoring
  labels:
    file-system: ext4
    physical-volume: lvm-partition
    max-size: 20Gi
    app: sb-11
spec:
  capacity:
    storage: 20Gi
  volumeMode: Filesystem
  accessModes:
  - ReadWriteOnce
  persistentVolumeReclaimPolicy: Delete
  storageClassName: node0-local-storage-monitoring
  local:
    path: /home/zoosman/dev/k0s/volumes/mnt/monitoring
  nodeAffinity:
    required:
      nodeSelectorTerms:
      - matchExpressions:
        - key: kubernetes.io/hostname
          operator: In
          values:
          - mp8

...

---
apiVersion: v1
kind: Namespace
metadata:
  name: monitoring

...

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: monitoring-data
  namespace: monitoring
spec:
  selector:
    matchLabels:
      app: sb-11
  storageClassName: node0-local-storage-monitoring
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi

...

---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: sb-11
    test: liveness
  name: monitoring-sb-11
  namespace: monitoring
spec:
  replicas: 1
  selector:
    matchLabels:
      app: sb-11
  template:
    metadata:
      labels:
        app: sb-11
    spec:
      nodeSelector:
        node-type: worker
      restartPolicy: Always
      containers:
        # ---
        - name: prometheus
          image: reg.docker.askug.net:5000/prometheus-sb-11:0.0.0
          # command: [ "nohup", "/bin/sh", "-c" ]
          # args:
          #   ["while true; do rm -f /tmp/healthy; date > /tmp/healthy; sleep 7; done", "&"]
          #   # - touch /tmp/healthy; sleep 30; rm -f /tmp/healthy; sleep 600
          # livenessProbe:
          #   exec:
          #     command:
          #     - cat
          #     - /tmp/healthy
          #   initialDelaySeconds: 5
          #   periodSeconds: 5

          ports:
          - containerPort: 9090
            name: tcp9090

          env:
          - name: PROMETHEUS_VERSION
            value: 2.47.0

          resources:
            limits:
              memory: 4Gi
              cpu: 4

          volumeMounts:
            - mountPath: "/etc/prometheus/prometheus.yml"
              name: monitoring-data-volume
              subPath: "configurations/prometheus/prometheus.yml"
              readOnly: true
            - mountPath: "/var/lib/prometheus"
              name: monitoring-data-volume
              subPath: "caches/prometheus"

      volumes:
        - name: monitoring-data-volume
          persistentVolumeClaim:
            claimName: monitoring-data
...

---
apiVersion: v1
kind: Service
metadata:
  name: prometheus-srv-9090
  namespace: monitoring
spec:
  selector:
    app: sb-11
  type: LoadBalancer
  loadBalancerIP: 10.203.10.25
  ports:
    - protocol: TCP
      name: "http-9090"
      port: 9090
      targetPort: 9090

...

