---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: mmonitoring-service-account
  namespace: monitoring
automountServiceAccountToken: true

...


---
apiVersion: v1
kind: ConfigMap
metadata:
  name: prometheus-config
  namespace: monitoring
immutable: true
data:
  prometheus.yml: |+
    global:
      scrape_interval: 15s
      evaluation_interval: 25s

    #alerting:
    #  alertmanagers:
    #    - static_configs:
    #        - targets:
    #          - alertmanager:9093

    rule_files:
      # - "first_rules.yml"
      # - "second_rules.yml"

    scrape_configs:
      - job_name: "prometheus"
        static_configs:
          - targets: ["localhost:9090"]

...


---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: monitoring-data
  namespace: monitoring
spec:
  selector:
    matchLabels:
      app: sb-11
  storageClassName: node0-local-storage-monitoring
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi

...


---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  labels:
    app: sb-11
    test: liveness
  name: monitoring-sb-11
  namespace: monitoring
spec:
  serviceName: "monitroring-sb-11-service"
  replicas: 1
  selector:
    matchLabels:
      app: sb-11
  template:
    metadata:
      labels:
        app: sb-11
    spec:
      nodeSelector:
        node-type: worker
      restartPolicy: Always
      serviceAccountName: mmonitoring-service-account
      automountServiceAccountToken: true
      containers:
        # ---
        - name: prometheus
          image: reg.docker.askug.net:5000/prometheus-sb-11:0.0.0

          # command: [ "nohup", "/bin/sh", "-c" ]
          # args:
          #   ["while true; do rm -f /tmp/healthy; date > /tmp/healthy; sleep 7; done", "&"]
          #   # - touch /tmp/healthy; sleep 30; rm -f /tmp/healthy; sleep 600
          
          livenessProbe:
            httpGet:
              path: /-/healthy
              port: 9090
              httpHeaders:
              - name: Authorization
                value: "Bearer TokenXXXToken" # ToDo put the token to a secret
            initialDelaySeconds: 5
            periodSeconds: 5

          readinessProbe:
            httpGet:
              path: /-/ready
              port: 9090
              httpHeaders:
              - name: Authorization
                value: "Bearer TokenXXXToken" # ToDo put the token to a secret
            initialDelaySeconds: 3
            periodSeconds: 3

          ports:
          - containerPort: 9090
            name: tcp9090

          env:
          - name: PROMETHEUS_VERSION
            value: 2.47.0

          resources:
            limits:
              memory: 4Gi
              cpu: "4"

          volumeMounts:
            - mountPath: "/etc/prometheus/prometheus.yml"
              name: monitoring-data-config
              subPath: "prometheus.yml"
              readOnly: true
            - mountPath: "/var/lib/prometheus"
              name: monitoring-data-volume
              subPath: "caches/prometheus"

      volumes:
        - name: monitoring-data-config
          configMap:
            name: prometheus-config
        - name: monitoring-data-volume
          persistentVolumeClaim:
            claimName: monitoring-data
...

---
apiVersion: v1
kind: Service
metadata:
  name: prometheus-srv-9090
  namespace: monitoring
spec:
  selector:
    app: sb-11
  type: LoadBalancer
  loadBalancerIP: 10.203.10.25
  ports:
    - protocol: TCP
      name: "http-9090"
      port: 9090
      targetPort: 9090

...

