apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "monitoring.serviceAccountName" . }}
  namespace: {{ include "monitoring.namespace" . }}
  labels:
    {{- include "monitoring.labels" . | nindent 4 }}
automountServiceAccountToken: true
