apiVersion: v1
kind: PersistentVolume
metadata:
  name: m8-local-storage-monitoring
  labels:
    file-system: ext4
    physical-volume: lvm-partition
    max-size: {{ .Values.pv.capacity.storage }}
    {{- include "monitoring.labels" . | nindent 4 }}
spec:
  capacity:
    storage: {{ .Values.pv.capacity.storage }}
  volumeMode: {{ .Values.pv.volumeMode }}
  accessModes:
  - ReadWriteOnce
  persistentVolumeReclaimPolicy: Delete
  storageClassName: {{ .Values.pv.storageClass }}
  local:
    path: {{ .Values.pv.path }}
  nodeAffinity:
    required:
      nodeSelectorTerms:
      - matchExpressions:
        - key: kubernetes.io/hostname
          operator: In
          values:
          - {{ .Values.pv.node }}
