apiVersion: v1
kind: ConfigMap
metadata:
  name: prometheus-config
  namespace: {{ include "monitoring.namespace" . }}
  labels:
    {{- include "monitoring.labels" . | nindent 4 }}
immutable: true
data:
  # {{- $srv := upper (printf "%s-%.0f-service" "pushgateway-srv" .Values.pushgateway.service.port) | replace "-" "_" }}
  prometheus.yml: |+
    global:
      scrape_interval: 15s
      evaluation_interval: 25s

    #alerting:
    #  alertmanagers:
    #    - static_configs:
    #        - targets:
    #          - alertmanager:9093

    rule_files:
      # - "first_rules.yml"
      # - "second_rules.yml"

    scrape_configs:
      - job_name: "Prometheus"
        static_configs:
          - targets: ["localhost:9090"]
      - job_name: "Pushgateway"
        honor_labels: true
        static_configs:
        - targets: ["{{ printf "pushgateway-srv-%.0f.%s.%s:%.0f" .Values.pushgateway.service.port (include "monitoring.namespace" .) .Values.global.clusterDomainName .Values.pushgateway.service.port }}"]

