apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: monitoring-data
  namespace: {{ include "monitoring.namespace" . }}
  labels:
    {{- include "monitoring.labels" . | nindent 4 }}
spec:
  selector:
    matchLabels:
      app: {{ include "monitoring.fullname" . }}
  storageClassName: {{ .Values.pv.storageClass }}
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
