apiVersion: apps/v1
kind: StatefulSet
metadata:
  labels:
    {{- include "monitoring.labels" . | nindent 4 }}
    test: liveness
  name: {{ printf "%s-%s" "pushgateway" (include "monitoring.statefullSetName" .) | trunc 63 | trimSuffix "-" }}
  namespace: {{ include "monitoring.namespace" . }}
spec:
  serviceName: {{ printf "%s-%s" "pushgateway" (include "monitoring.statefullSetServiceName" .) | trunc 63 | trimSuffix "-" }}
  replicas: {{ .Values.pushgateway.replicaCount }}
  selector:
    matchLabels:
      app: {{ include "monitoring.fullname" . }}
  template:
    metadata:
      labels:
        {{- include "monitoring.selectorLabels" . | nindent 8 }}
    spec:
      nodeSelector:
        node-type: {{ .Values.global.nodeSelector }}
      restartPolicy: Always
      serviceAccountName: {{ include "monitoring.serviceAccountName" . }}
      automountServiceAccountToken: true
      containers:
        # ---
        - name: pushgateway
          image: {{ printf "%s/%s:%s" .Values.global.repository .Values.pushgateway.image.name (default .Chart.Version .Values.pushgateway.image.tag) }}

          # command: [ "nohup", "/bin/sh", "-c" ]
          # args:
          #   ["while true; do rm -f /tmp/healthy; date > /tmp/healthy; sleep 7; done", "&"]
          #   # - touch /tmp/healthy; sleep 30; rm -f /tmp/healthy; sleep 600
          
          livenessProbe:
            httpGet:
              path: /-/healthy
              port: {{ .Values.pushgateway.service.port }}
            initialDelaySeconds: 5
            periodSeconds: 5

          readinessProbe:
            httpGet:
              path: /-/ready
              port: {{ .Values.pushgateway.service.port }}
            initialDelaySeconds: 3
            periodSeconds: 3

          ports:
          - containerPort: {{ .Values.pushgateway.service.port }}
            name: {{ printf "%s-%.0f" "tcp" .Values.pushgateway.service.port }}

          env:
          - name: PUSHGATEWAY_VERSION
            value: 1.6.2 # ToDo remove verison into vars

          resources:
            limits:
            {{- with .Values.pushgateway.resources.limits -}}
            {{- toYaml . | nindent 14 }}
            {{- end }}
            requests:
            {{- with .Values.pushgateway.resources.requests -}}
            {{- toYaml . | nindent 14 }}
            {{- end }}

