apiVersion: v1
kind: Service
metadata:
  name: {{ printf "%s-%.0f" "pushgateway-srv" .Values.pushgateway.service.port }}
  namespace: {{ include "monitoring.namespace" . }}
  labels:
    {{- include "monitoring.labels" . | nindent 4 }}
spec:
  selector:
    app: {{ include "monitoring.fullname" . }}
  {{- if contains "LoadBalancer" .Values.pushgateway.service.type }}
  type: LoadBalancer
  loadBalancerIP: {{ .Values.pushgateway.service.loadBalancerIP }}
  {{- else if contains "NodePort" .Values.pushgateway.service.type }}
  type: NodePort
  {{- else if contains "ClusterIP" .Values.pushgateway.service.type }}
  type: ClusterIP
  {{- end }}
  ports:
    - protocol: TCP
      name: {{ printf "%s-%.0f" "http" .Values.pushgateway.service.port }}
      port: {{ .Values.pushgateway.service.port }}
      targetPort: {{ .Values.pushgateway.service.port }}
      {{- if and (or (contains "NodePort" .Values.pushgateway.service.type) (contains "ClusterIP" .Values.pushgateway.service.type)) .Values.pushgateway.service.nodePort }}
      nodePort: {{ .Values.pushgateway.service.nodePort }}
      {{- end }}
      