---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: m8-local-storage-docker-registry
  labels:
    file-system: ext4
    physical-volume: lvm-partition
    max-size: 30GiB
    app: docker-registry
spec:
  capacity:
    storage: 20Gi
  volumeMode: Filesystem
  accessModes:
  - ReadWriteOnce
  persistentVolumeReclaimPolicy: Delete
  storageClassName: node0-local-storage-docker-registry
  local:
    path: /home/zoosman/dev/k0s/volumes/mnt/docker
  nodeAffinity:
    required:
      nodeSelectorTerms:
      - matchExpressions:
        - key: kubernetes.io/hostname
          operator: In
          values:
          - mp8

...
